#Travis CI

language: php

php:
 - 5.6

branches:
 - master

before_script:
 - phpenv config-rm xdebug.ini
 - mkdir plugins
 - wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.9.0/DevTools_v1.9.0.phar
 - pecl install channel://pecl.php.net/pthreads-2.0.10
 - pecl install channel://pecl.php.net/weakref-0.2.6
 - echo | pecl install channel://pecl.php.net/yaml-1.1.1
 - git clone https://github.com/ClearSkyTeam/CI-Test

script:
 - php CI-Test/Travis.php
 
notifications:
 email: false
